import {NextRequest,NextResponse} from 'next/server';
import {mutate,readState} from '@/lib/store';
import {validSignature,applyPayment,applyRefund} from '@/lib/orders';
import {flushImmediateJobs} from '@/lib/delivery';
import {razorpay,assertAccount} from '@/lib/razorpay';
export async function POST(req:NextRequest){const secret=process.env.RAZORPAY_WEBHOOK_SECRET;if(!secret)return NextResponse.json({error:'Webhook not configured'},{status:503});if(Number(req.headers.get('content-length')||0)>262144)return new NextResponse(null,{status:413});const raw=await req.text();if(raw.length>262144)return new NextResponse(null,{status:413});if(!validSignature(raw,req.headers.get('x-razorpay-signature')||'',secret))return new NextResponse(null,{status:401});try{const event=JSON.parse(raw);if(!['payment.authorized','payment.captured','payment.failed','order.paid','refund.created','refund.processed','refund.failed'].includes(event.event))return NextResponse.json({ignored:true});const id=req.headers.get('x-razorpay-event-id');if(!id||id.length>200)return new NextResponse(null,{status:400});let payment=event.payload?.payment?.entity;const refund=event.payload?.refund?.entity;if(refund&&!payment){if(!/^pay_[A-Za-z0-9]+$/.test(refund.payment_id))return new NextResponse(null,{status:400});payment=await razorpay('payments/'+refund.payment_id);}if(!payment)return new NextResponse(null,{status:400});const known=(await readState()).orders?.find(o=>o.providerOrderId===payment.order_id);if(!known||known.gateway!=='razorpay')return NextResponse.json({ignored:true});assertAccount(known);let flushIds:string[]=[];
 await mutate(s=>{const o=s.orders!.find(o=>o.id===known.id)!;if(o.events.some(e=>e.id===id))return;const wasPaid=['paid','partially_refunded'].includes(o.status);applyPayment(s,o,payment,refund?id+':payment':id);if(refund)applyRefund(s,o,refund,id);if(!wasPaid&&['paid','partially_refunded'].includes(o.status)&&o.mode==='live')flushIds=[`purchase:${o.id}`,`staff-purchase:${o.id}`];});
 if(flushIds.length)await flushImmediateJobs(flushIds);
 return NextResponse.json({received:true});}catch{return NextResponse.json({error:'Event not processed; retry required'},{status:500});}}
