import {test} from 'node:test';import assert from 'node:assert/strict';import {siteSchema} from '../lib/schema';import {seed} from '../lib/seed';import {instagramUrl,validateMedia,mediaLimit,parseMediaFolder} from '../lib/media-rules';import {mediaObjectPath} from '../lib/media-storage';
const artist={id:'a',name:'Example',city:'Delhi',image:'/hero.png',profileUrl:'',amountPaise:null,definition:'Gross booking value',period:'',evidence:'',consent:false,approved:false,expires:'',video:'',poster:'',transcript:''};
test('older artist records remain valid',()=>assert.ok(siteSchema.safeParse({...seed,artists:[artist]}).success));
test('artist bio, handle and gallery survive schema parsing',()=>{const a={...artist,bio:'Bridal artist',instagram:'@artist.name',gallery:[{image:'/hero.png',caption:'Bridal look'}]};const s=siteSchema.parse({...seed,artists:[a]});assert.deepEqual(s.artists[0],{...a,featuredTopGrossing:false});});
test('invalid handles and oversized galleries are rejected',()=>{assert.equal(siteSchema.safeParse({...seed,artists:[{...artist,instagram:'https://evil.test'}]}).success,false);assert.equal(siteSchema.safeParse({...seed,artists:[{...artist,gallery:Array(7).fill({image:'/hero.png',caption:''})}]}).success,false);assert.equal(instagramUrl('javascript:alert(1)'), '');assert.equal(instagramUrl('@artist.name'),'https://www.instagram.com/artist.name/');});
test('upload allows supported formats up to 20MB only',()=>{assert.equal(validateMedia('video/mp4',mediaLimit),'mp4');assert.throws(()=>validateMedia('image/svg+xml',100));assert.throws(()=>validateMedia('image/png',0));assert.throws(()=>validateMedia('image/png',mediaLimit+1));});
test('media folders are validated and paths are prefixed',()=>{assert.equal(parseMediaFolder('artists'),'artists');assert.equal(parseMediaFolder('testimonials'),'testimonials');assert.equal(parseMediaFolder('site'),'site');assert.equal(parseMediaFolder('evil'),'site');assert.match(mediaObjectPath('artists','jpg'),/^artists\/[a-f0-9-]+\.jpg$/);assert.match(mediaObjectPath('testimonials','mp4'),/^testimonials\/[a-f0-9-]+\.mp4$/);});
import {matchingExamples} from '../lib/enquiry-demo';
test('demo location date and budget filters combine and reset',()=>{const rows=[{id:1,city:'Delhi',date:'2027-02-14',budget:25000,title:'Bridal'},{id:2,city:'Mumbai',date:'2027-03-06',budget:15000,title:'Event'}];assert.equal(matchingExamples(rows,'Delhi','2027-02-14',20000).length,1);assert.equal(matchingExamples(rows,'Delhi','2027-03-06',0).length,0);assert.equal(matchingExamples(rows,'','',0).length,2);});
