import {test} from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {initialState} from '../lib/seed';import {quote} from '../lib/commerce';import {reserveOrder,bindProviderOrder,applyPayment,applyRefund,validSignature,abandonUnpaidCheckout,activeOrderForCart} from '../lib/orders';import {ordersCsv,capturedTotal,refundedTotal} from '../lib/order-report';import {eligible} from '../lib/workflows';
const payCtx={gateway:'razorpay' as const,keyId:'rzp_live_fixture',mode:'live' as const};
function fixture(){const s=initialState();s.published.settings.policiesApproved=true;const p=s.published.plans.find(p=>p.id==='pro')!;p.approved=true;p.pricePaise=1899900;const c={id:'cart1',tokenHash:'private',name:'Artist',business:'Studio',email:'artist@example.com',phone:'9999999999',planId:p.id,planVersion:p.version,marketing:false,terms:true,coupon:'',...quote(p),status:'open' as const,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};s.carts.push(c);const o=reserveOrder(s,c,payCtx).order;bindProviderOrder(o,{id:'order_123',amount:o.total,currency:'INR',receipt:o.id});return {s,c,o,p};}
const pay=(amount=1899900,status='captured')=>({id:'pay_123',order_id:'order_123',amount,currency:'INR',status,method:'upi',created_at:1789999999});
test('snapshot retains purchased price and one order per cart',()=>{const {s,c,o,p}=fixture();p.pricePaise=999;p.features.push('Changed');assert.equal(o.total,1899900);assert.notDeepEqual(o.plan.features,p.features);assert.equal(reserveOrder(s,c,payCtx).order.id,o.id);assert.equal(s.orders?.length,1);});
test('capture is idempotent and late failures cannot downgrade it',()=>{const {s,o,c}=fixture();applyPayment(s,o,pay(),'evt1');applyPayment(s,o,pay(),'evt1');applyPayment(s,o,pay(1899900,'failed'),'evt2');assert.equal(o.status,'paid');assert.equal(c.status,'paid');assert.equal(o.attempts.length,1);assert.equal(s.jobs.filter(j=>j.kind==='purchase').length,1);assert.equal(eligible(s,s.jobs.find(j=>j.kind==='purchase')!),true);});
test('authorized is not paid and amount/currency/order mismatch cannot mark paid',()=>{let {s,o}=fixture();applyPayment(s,o,pay(1899900,'authorized'),'evt');assert.equal(o.status,'pending');assert.equal(capturedTotal(o),0);assert.equal(s.jobs.length,0);applyPayment(s,o,pay(100),'bad');assert.equal(o.status,'needs_review');assert.equal(capturedTotal(o),0);assert.throws(()=>applyPayment(s,o,{...pay(),order_id:'order_other'},'wrong'));});
test('partial/full refunds deduplicate and cannot regress after delayed events',()=>{const {s,o}=fixture();applyPayment(s,o,pay(),'p');const r={id:'rfnd_1',payment_id:'pay_123',amount:10000,status:'processed',created_at:1789999999};applyRefund(s,o,r,'r1');applyRefund(s,o,r,'r1');applyRefund(s,o,{...r,status:'created'},'r2');assert.equal(refundedTotal(o),10000);assert.equal(o.status,'partially_refunded');applyRefund(s,o,{...r,id:'rfnd_2',amount:o.total-10000},'r3');assert.equal(o.status,'refunded');assert.equal(eligible(s,s.jobs.find(j=>j.kind==='purchase')!),false);applyPayment(s,o,pay(),'late');assert.equal(o.status,'refunded');});
test('multiple captures go to review instead of silently becoming normal sales',()=>{const {s,o}=fixture();applyPayment(s,o,pay(),'1');applyPayment(s,o,{...pay(),id:'pay_456'},'2');assert.equal(o.status,'needs_review');assert.equal(capturedTotal(o),o.total*2);});
test('test payments never queue real thank-you emails',()=>{const {s,o}=fixture();o.mode='test';applyPayment(s,o,pay(),'p');assert.equal(s.jobs.length,0);});
test('raw HMAC accepts only genuine exact bytes',()=>{const raw='{"x":1}',secret='test-secret',sig=createHmac('sha256',secret).update(raw).digest('hex');assert.ok(validSignature(raw,sig,secret));assert.ok(!validSignature(raw+' ',sig,secret));assert.ok(!validSignature(raw,'garbage',secret));assert.ok(!validSignature(raw,sig,'wrong'));});
test('CSV exports exact amounts and escapes formula injection',()=>{const {o}=fixture();o.customer.name='=1+1';o.customer.business='A, "B"';const csv=ordersCsv([o]);assert.ok(csv.includes('"\'=1+1"'));assert.ok(csv.includes('"A, ""B"""'));assert.ok(csv.includes('18999'));assert.ok(!csv.includes('private'));});
test('coupon reservation counts pending orders, not just completed carts',()=>{const {s,o,p}=fixture();const coupon={id:'offer',code:'TEN',kind:'percent' as const,value:10,maxDiscountPaise:null,minimumPaise:0,plans:[],starts:'2020-01-01',ends:'2030-01-01',limit:1,perCustomer:1,enabled:true};s.published.coupons.push(coupon);o.coupon=structuredClone(coupon);const c={...s.carts[0],id:'second',status:'open' as const,coupon:'TEN',...quote(p,coupon)};s.carts.push(c);assert.throws(()=>reserveOrder(s,c,payCtx),/redemption limit/);});
test('unapproved policy, stale quote, missing consent and Privy cannot charge',()=>{for(const field of ['policy','quote','consent','privy']){const {s,p}=fixture();s.orders=[];const c={...s.carts[0],id:'new',status:'open' as const};s.carts=[c];if(field==='policy')s.published.settings.policiesApproved=false;if(field==='quote')p.version++;if(field==='consent')c.terms=false;if(field==='privy')c.planId='privy';assert.throws(()=>reserveOrder(s,c,payCtx));}});
test('customer can abandon unpaid checkout and reserve a fresh order',()=>{const {s,c,o}=fixture();assert.equal(c.status,'pending');abandonUnpaidCheckout(s,c);assert.equal(o.status,'cancelled');assert.equal(c.status,'open');assert.equal(activeOrderForCart(s,c.id),undefined);const next=reserveOrder(s,c,payCtx);assert.equal(next.created,true);assert.notEqual(next.order.id,o.id);assert.equal(s.orders?.filter(x=>x.cartId===c.id).length,2);});
