import {NextRequest,NextResponse} from 'next/server';import {z} from 'zod';import {requireRole} from '@/lib/auth';import {readState,mutate} from '@/lib/store';import {sameOrigin,json,fail} from '@/lib/api';import {rateLimit} from '@/lib/limit';import {aiConfigured,aiEnabled,aiModel,aiDailyLimit,openai} from '@/lib/openai';import {documentLimit,validDocument} from '@/lib/assistant-ai';
export const maxDuration=60;
export async function GET(){try{await requireRole(['admin']);const s=await readState();return NextResponse.json({configured:aiConfigured(),enabled:aiEnabled(),model:aiModel(),dailyLimit:aiDailyLimit(),used:s.aiUsage?.day===new Date().toISOString().slice(0,10)?s.aiUsage.count:0,ready:Boolean(s.knowledge?.storeId),files:s.knowledge?.files||[]},{headers:{'Cache-Control':'no-store'}});}catch(e){return fail(e,403);}}
export async function POST(req:NextRequest){try{sameOrigin(req);const staff=await requireRole(['admin']);await rateLimit(req,'knowledge-admin',60);
 if(req.headers.get('content-type')?.includes('multipart/form-data')){if(Number(req.headers.get('content-length')||0)>documentLimit+20000)throw new Error('Maximum document size is 4 MB.');const chunks:Uint8Array[]=[];let bytes=0;const reader=req.body?.getReader();if(!reader)throw new Error('Missing upload');while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>documentLimit+20000){await reader.cancel();throw new Error('Maximum document size is 4 MB.');}chunks.push(value);}const form=await new Response(Buffer.concat(chunks),{headers:{'Content-Type':req.headers.get('content-type')!}}).formData();const file=form.get('file');if(!(file instanceof File)||!validDocument(file.name,file.size))throw new Error('Upload a PDF, DOCX, TXT or MD file up to 4 MB.');if(form.get('approved')!=='true')throw new Error('Confirm that the document is approved for customer-facing answers.');const state=await readState();if(!state.knowledge?.storeId)throw new Error('Create the document library first.');if(state.knowledge.files.length>=20)throw new Error('Remove an existing document before uploading more (20 maximum).');const upload=new FormData();upload.append('file',file);upload.append('purpose','assistants');const uploaded=await openai('files',{method:'POST',form:upload});const id=crypto.randomUUID();try{const entry=await openai(`vector_stores/${state.knowledge.storeId}/files`,{method:'POST',body:{file_id:uploaded.id,attributes:{document_id:id}}});await mutate(s=>{if(!s.knowledge||s.knowledge.files.length>=20)throw new Error('Document limit reached');s.knowledge.files.push({id,fileId:uploaded.id,name:file.name.slice(0,200),status:entry.status||'in_progress',enabled:false,created_at:new Date().toISOString()});});}catch(e){await openai(`files/${uploaded.id}`,{method:'DELETE'}).catch(()=>{});throw e;}return NextResponse.json({ok:true});}
 const body=z.object({action:z.enum(['connect','setup','refresh','enable','remove']),id:z.string().uuid().optional(),enabled:z.boolean().optional()}).parse(await json(req));let state=await readState();
 if(body.action==='connect'){await openai('models/'+encodeURIComponent(aiModel()));return NextResponse.json({message:'API key and model access verified. Test an answer below to verify generation.'});}
 if(body.action==='setup'){if(!state.knowledge?.storeId){const store=await openai('vector_stores',{method:'POST',body:{name:'OLREADY sales assistant'}});const kept=await mutate(s=>{if(s.knowledge?.storeId)return false;s.knowledge={storeId:store.id,files:[]};return true;});if(!kept)await openai(`vector_stores/${store.id}`,{method:'DELETE'});}return NextResponse.json({ok:true});}
 if(!state.knowledge)throw new Error('Create the document library first.');
 if(body.action==='refresh'){const results=await Promise.all(state.knowledge.files.map(async f=>{try{const entry=await openai(`vector_stores/${state.knowledge!.storeId}/files/${f.fileId}`);return {id:f.id,status:entry.status};}catch{return {id:f.id,status:'unavailable'};}}));await mutate(s=>{for(const r of results){const f=s.knowledge?.files.find(f=>f.id===r.id);if(f)f.status=r.status;}});return NextResponse.json({ok:true});}
 const file=state.knowledge.files.find(f=>f.id===body.id);if(!file)throw new Error('Document not found');
 if(body.action==='enable'){if(body.enabled===undefined)throw new Error('Choose document availability');if(body.enabled){const entry=await openai(`vector_stores/${state.knowledge.storeId}/files/${file.fileId}`);if(entry.status!=='completed')throw new Error('Document processing is not complete. Refresh its status.');}await mutate(s=>{const f=s.knowledge?.files.find(f=>f.id===file.id);if(!f)throw new Error('Document no longer exists');f.enabled=body.enabled!;if(body.enabled)f.status='completed';s.audit.unshift({at:new Date().toISOString(),by:staff.id,action:`Document ${f.name}: ${f.enabled?'enabled':'disabled'}`});s.audit=s.audit.slice(0,1000);});}
 if(body.action==='remove'){await mutate(s=>{const f=s.knowledge?.files.find(f=>f.id===file.id);if(f)f.enabled=false;});await openai(`files/${file.fileId}`,{method:'DELETE'});await mutate(s=>{if(s.knowledge)s.knowledge.files=s.knowledge.files.filter(f=>f.id!==file.id);});}
 return NextResponse.json({ok:true});
 }catch(e){return fail(e);}}
