'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Play} from '@phosphor-icons/react';
import type {Site} from '@/lib/schema';
import {featuredArtist} from '@/lib/artist-catalog';
import {artistPath,cityPath} from '@/lib/seo';
import {ArtistResultContact} from './ArtistResultContact';
import {ArtistSocialRow} from './ArtistSocialRow';
import {track} from '@/lib/client-events';
import {useState} from 'react';

function Photo({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}){return <Image className={className} src={src} alt={alt} width={900} height={1100} sizes="(max-width: 760px) 100vw, 720px" priority={priority} unoptimized/>;}

export function ArtistProfile({site,artist}:{site:Site;artist:Site['artists'][number]}){const [video,setVideo]=useState(false);const services=artist.services?.filter(Boolean)||[];const clips=featuredArtist(artist)?(site.testimonials||[]).filter(t=>t.artistId===artist.id):[];return <article className="section artist-profile"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><Link href="/top-grossing-artists">Top Grossing Artists</Link><span aria-hidden="true">/</span><span aria-current="page">{artist.name}</span></nav><div className="artist-profile-grid">{artist.image&&<Photo src={artist.image} alt={`${artist.name}, makeup artist in ${artist.city}`} className="artist-profile-photo" priority/>}<div><p className="eyebrow">MAKEUP ARTIST · {artist.city.toUpperCase()}</p><h1>{artist.name}</h1><p className="lead">{artist.bio||`${artist.name} is a featured makeup artist on OLREADY.`}</p>{!!services.length&&<p className="artist-services">{services.join(' · ')}</p>}<ArtistSocialRow artist={artist} profileLabel="View profile" onInstagramClick={()=>track('instagram_click',artist.id)} onProfileClick={()=>track('merchant_click','artist_profile')}/><ArtistResultContact site={site} artist={artist} label={site.copy.askResults||'Ask about artist results'}/>{artist.video&&<button className="button" type="button" onClick={()=>{setVideo(true);track('video_play',artist.id);}}><Play weight="fill"/> Watch {artist.name}&apos;s story</button>}</div></div>{!!artist.gallery?.filter(g=>g.image).length&&<section className="artist-portfolio open"><h2>Portfolio</h2><div className="artist-portfolio-grid">{artist.gallery.filter(g=>g.image).map((g,i)=><figure key={i}><Photo src={g.image} alt={g.caption||`${artist.name} portfolio ${i+1}`}/>{g.caption&&<figcaption>{g.caption}</figcaption>}</figure>)}</div></section>}{artist.video&&<section className="artist-profile-video"><h2>Artist story</h2><video controls preload="metadata" src={artist.video} poster={artist.poster||artist.image}/>{artist.transcript&&<details><summary>Read transcript</summary><p>{artist.transcript}</p></details>}</section>}{clips.map(t=><section className="artist-profile-video" key={t.id}><h2>{t.title}</h2><video controls preload="metadata" src={t.video} poster={t.poster||artist.image}/>{t.caption&&<p>{t.caption}</p>}</section>)}<footer className="artist-profile-footer"><Link href={cityPath(artist.city)}>More makeup artists in {artist.city}</Link><Link href="/plans" className="button primary">Compare OLREADY plans<ArrowRight/></Link></footer>{video&&artist.video&&<div className="overlay"><div className="dialog wide" role="dialog" aria-modal="true" aria-label={artist.name}><button className="icon close" onClick={()=>setVideo(false)} aria-label="Close video">×</button><video controls autoPlay src={artist.video} poster={artist.poster}/></div></div>}</article>;}
