'use client';
import {ProviderComparison} from './Refinements';
import {EnquiryDemo} from './EnquiryDemo';
import {TestimonialScroll} from './TestimonialScroll';
import {useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Check,ShieldCheck,MapPin,CalendarBlank,ChatCircleText,Sparkle,GlobeHemisphereWest,Headset,UserCircle,Diamond} from '@phosphor-icons/react';
import type {Site} from '@/lib/schema';
import {money} from '@/lib/commerce';
import {track} from '@/lib/client-events';
const whatsapp=(site:Site,message:string)=>`https://wa.me/${site.settings.whatsapp}?text=${encodeURIComponent(message)}`;
export function BrandPhoto({site,className=''}:{site:Site;className?:string}){const [failed,setFailed]=useState(false);return <Image src={failed?'/hero.png':site.settings.heroImage||'/hero.png'} alt="Makeup artist holding brushes, framed by a chrome and pink ribbon" width={900} height={1100} sizes="(max-width:760px) 100vw, 50vw" unoptimized priority className={className} onError={()=>setFailed(true)}/>}
export function SalesHero({site,demo}:{site:Site;demo:boolean}){const c=site.copy,p=site.pages.find(p=>p.slug==='/')!;return <section className="sales-hero"><div className="sales-hero-copy"><p className="eyebrow">{p.eyebrow}</p><h1>{p.heading}<br/><em>{p.accent}</em></h1><p className="sales-lead">{p.body}</p><div className="actions"><Link href={p.primaryHref} className="button primary">{p.primaryLabel}<ArrowRight/></Link><Link href={p.secondaryHref} className="text-link">{p.secondaryLabel}<ArrowUpRight/></Link></div>{c.salesMicro?.trim()&&<p className="sales-micro">{c.salesMicro}</p>}{site.metrics.length>0&&<div className="sales-proof-numbers">{site.metrics.map(m=><div key={m.id}><strong>{m.value}{demo&&!m.approved?'*':''}</strong><span>{m.label}</span>{m.period&&<small>{m.period}</small>}</div>)}</div>}{demo&&site.metrics.some(m=>!m.approved)&&<small className="sales-development">*Development figures awaiting evidence approval.</small>}</div><div className="sales-hero-visual"><BrandPhoto site={site}/><div className="sales-glass-tag"><ShieldCheck weight="duotone" size={30}/><span>{c.salesBriefStatus}<small>{c.salesStep3}</small></span></div></div></section>}
export function EnquiryVisual({site}:{site:Site}){const c=site.copy;return <div className="enquiry-scene"><div className="enquiry-card"><div className="enquiry-brand"><span>{site.settings.brand}</span><Sparkle size={21}/></div><span className="enquiry-status"><ShieldCheck size={16}/>{c.salesBriefStatus}</span><h3>{c.salesBriefTitle}</h3>{[[MapPin,c.salesBriefLocation,c.salesBriefLocationValue],[CalendarBlank,c.salesBriefDate,c.salesBriefDateValue],[ChatCircleText,c.salesBriefBudget,c.salesBriefBudgetValue]].map(([Icon,label,value],i)=>{const Glyph=Icon as typeof MapPin;return <div className="enquiry-row" key={i}><Glyph size={22}/><div><small>{label as string}</small><strong>{value as string}</strong></div></div>})}<Link href="/how-it-works" className="button primary">{c.salesBriefAction}<ArrowRight/></Link></div><p className="enquiry-caption">{c.salesIllustration}</p></div>}
export function ProductStory({site}:{site:Site}){const c=site.copy;return <section className="section product-story"><div><p className="eyebrow">{c.salesProductLabel}</p><h2>{c.salesProductTitle}</h2><p className="sales-lead">{c.salesProductBody}</p><Link className="text-link" href="/how-it-works">{c.salesSecondary}<ArrowRight/></Link></div><EnquiryVisual site={site}/></section>}
export function ProcessStrip({site}:{site:Site}){const c=site.copy;return <section className="section process-strip"><p className="eyebrow">{c.salesProcessEyebrow}</p><h2>{c.salesProcessTitle}</h2><div className="process-strip-grid">{[ShieldCheck,GlobeHemisphereWest,ChatCircleText].map((Icon,i)=><article key={i}><div><Icon size={35} weight="duotone"/><span>0{i+1}</span></div><h3>{c['salesStep'+(i+1)]}</h3><p>{c['salesStep'+(i+1)+'Body']}</p></article>)}</div></section>}
export function PlanCards({site,full=false}:{site:Site;full?:boolean}){const c=site.copy;return <section className={'section clear-plans '+(full?'full-plans':'')} id="choose-plan"><div className="clear-plans-heading"><p className="eyebrow">{c.salesPlansEyebrow}</p>{full?<h1>{c.salesPlansTitle}</h1>:<h2>{c.salesPlansTitle}</h2>}<p>{c.salesPlansBody}</p></div><div className="clear-plan-grid">{site.plans.map((p,i)=>{const enquiry=p.features.find(f=>/\d.*(enquir|leads)/i.test(f));const Icon=[Sparkle,GlobeHemisphereWest,Diamond][i]||Sparkle;return <article className={'clear-plan clear-plan-'+p.id+(p.featured?' is-featured':'')} key={p.id}><div className="clear-plan-art"><div className="plan-insignia"><Icon size={54} weight="duotone"/></div><span>{p.tagline}</span><h2>{p.name}</h2><p>{p.description}</p></div><div className="clear-plan-content"><div className="plan-allowance"><strong>{enquiry?.match(/\d+/)?.[0]||'—'}</strong><span>{c.pitchAllowance}<small>{p.term}</small></span></div><div className="clear-plan-price">{p.approved?money(p.pricePaise):site.settings.pricePending}</div><small className="tax-included">{p.taxPercent}% GST included</small>{full?<><ul>{p.features.filter(f=>f!==enquiry).map((f,k)=><li key={k}><Check/>{f}</li>)}</ul>{p.id==='privy'?<a className="button primary" href={whatsapp(site,'Hi OLREADY, I would like to request an invitation to Privy.')} onClick={()=>track('whatsapp_click','privy_invitation')}>{c.inviteButton}<ArrowUpRight/></a>:<Link className="button primary" href={`/checkout?plan=${p.id}`} onClick={()=>track('plan_selected',p.id)}>{c.salesPlanButton}<ArrowRight/></Link>}<details><summary>{c.salesPlanDetails}</summary><p>{p.description}</p><p>{p.geography}</p><p>{p.leadModel}</p><p>{p.exclusions}</p><p>{p.renewal}</p></details></>:<Link className="button" href="/plans" onClick={()=>track('plan_selected',p.id)}>{c.salesPrimary}<ArrowRight/></Link>}</div></article>})}</div><p className="footnote">{c.salesPlanNote}</p>{full&&<div className="plan-human"><div><h3>{c.salesHuman}</h3><p>{c.salesHumanBody}</p></div><a className="button" href={whatsapp(site,'Hi OLREADY, help me choose a plan for my city and the clients I want to reach.')} onClick={()=>track('whatsapp_click','plans_fit')}>{c.salesHumanButton}<ArrowUpRight/></a></div>}</section>}
export function JoiningSteps({site}:{site:Site}){const c=site.copy;return <section className="section joining-steps"><h2>{c.salesJoinTitle}</h2><div>{[1,2,3].map(i=><article key={i}><span>0{i}</span><h3>{c['salesJoin'+i]}</h3><p>{c['salesJoin'+i+'Body']}</p></article>)}</div><a className="text-link" href={site.settings.merchantUrl} onClick={()=>track('merchant_click','joining_steps')}>{c.salesJoinProfile}<ArrowUpRight/></a></section>}
export function SalesClosing({site}:{site:Site}){const c=site.copy;return <section className="section sales-closing"><Sparkle size={45} weight="duotone"/><h2>{c.salesFinalTitle}</h2><p>{c.salesFinalBody}</p><Link className="button primary" href="/plans">{c.salesPrimary}<ArrowRight/></Link></section>}
export function BenefitsExperience({site}:{site:Site}){const c=site.copy;return <><section className="section benefits-intro"><div><p className="eyebrow">{c.salesBenefitsEyebrow}</p><h1>{c.salesBenefitsTitle}</h1><p className="sales-lead">{c.salesBenefitsBody}</p><Link href="/plans" className="button primary">{c.salesBenefitsCta}<ArrowRight/></Link><a className="text-link benefits-demo-link" href="#enquiry-demo">{c.demoButton}<ArrowRight/></a></div><EnquiryVisual site={site}/></section><section className="section benefit-bento"><article className="benefit-photo"><BrandPhoto site={site}/><div><UserCircle size={30}/><h2>{c.salesBenefit4}</h2><p>{c.salesBenefit4Body}</p></div></article><article className="benefit-tile benefit-pink"><ShieldCheck size={48} weight="duotone"/><h2>{c.salesBenefit1}</h2><p>{c.salesBenefit1Body}</p></article><article className="benefit-tile benefit-cream"><GlobeHemisphereWest size={48} weight="duotone"/><h2>{c.salesBenefit2}</h2><p>{c.salesBenefit2Body}</p></article><article className="benefit-support"><div className="support-symbol"><strong>RM</strong><span>{c.benefitRmLabel}</span></div><div><p className="eyebrow">{c.salesSupportLabel}</p><h2>{c.salesBenefit3}</h2><p>{c.salesBenefit3Body}</p><small>{c.salesSupportCaption}</small></div></article></section><section className="section verification-feature"><div className="verification-emblem" aria-hidden="true"><ShieldCheck size={76} weight="duotone"/><strong>3</strong></div><div><p className="eyebrow">{c.howStep2}</p><h2>{c.benefitVerifyTitle}</h2><p>{c.benefitVerifyBody}</p><Link className="text-link" href="/how-it-works">{c.benefitVerifyButton}<ArrowRight/></Link></div></section><section className="section matching-feature"><h2>{c.benefitMatchTitle}</h2><p>{c.benefitMatchBody}</p><div>{[[MapPin,c.benefitMatchLocation],[CalendarBlank,c.benefitMatchDate],[Sparkle,c.benefitMatchBudget]].map(([Icon,label],i)=>{const Glyph=Icon as typeof MapPin;return <article key={i}><Glyph size={35} weight="duotone"/><h3>{label as string}</h3></article>})}</div></section><ProviderComparison site={site}/><EnquiryDemo site={site}/><TestimonialScroll site={site}/><SalesClosing site={site}/></>}
export function EvidenceFallback({site}:{site:Site}){const c=site.copy;return <section className="section evidence-fallback"><div><p className="eyebrow">{c.artistEyebrow}</p><h2>{c.salesProofTitle}</h2><p>{c.salesProofBody}</p><a className="button" href={whatsapp(site,'Hi OLREADY, I would like to see available artist references and understand their results.')} onClick={()=>track('whatsapp_click','artist_references')}>{c.salesProofButton}<ArrowUpRight/></a></div><ShieldCheck size={110} weight="duotone"/></section>}
