'use client';
import {useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,ArrowUpRight,Check,ShieldCheck,ChatCircleText,SlidersHorizontal,Users,Diamond,Sparkle,GlobeHemisphereWest} from '@phosphor-icons/react';
import type {Site} from '@/lib/schema';
import {money} from '@/lib/commerce';
import {JoiningSteps,BrandPhoto} from './Conversion';
import {track} from '@/lib/client-events';
const icons=[Sparkle,ShieldCheck,GlobeHemisphereWest,ChatCircleText,Users];
export function PlansExperience({site}:{site:Site}){
 const [selected,setSelected]=useState(site.plans[0]?.id);const c=site.copy;const p=site.plans.find(p=>p.id===selected)||site.plans[0];if(!p)return null;
 const enquiry=p.features.find(f=>/\d.*(enquir|leads)/i.test(f));const allowance=enquiry?.match(/\d+/)?.[0];
 return <div className={'pitch-experience '+(!site.settings.motion?'motion-off':'')}><section className="pitch-hero section"><p className="eyebrow">{c.pitchPlansEyebrow}</p><h1>{c.pitchPlansTitle}</h1><p className="pitch-intro">{c.pitchPlansBody}</p><div className="actions"><a className="button primary" href="#plan-studio">{c.pitchPlansButton}<ArrowRight/></a><Link className="text-link" href="/how-it-works">{c.pitchPlansSecondary}<ArrowUpRight/></Link></div><div className="plan-orbit" aria-hidden="true">{site.plans.map((plan,i)=><div className={'membership membership-'+plan.id} key={plan.id}><span>{site.settings.brand}<Sparkle size={18}/></span><strong>{plan.name}</strong><small>{plan.tagline}</small><div className="membership-base"><span>{plan.term}</span><span>0{i+1}</span></div></div>)}</div></section>
 <section className="section plan-studio" id="plan-studio"><p className="eyebrow">{c.pitchSelectLabel}</p><div className="plan-switch" role="group" aria-label={c.pitchSelectLabel}>{site.plans.map(plan=><button key={plan.id} aria-pressed={plan.id===p.id} onClick={()=>{setSelected(plan.id);track('plan_selected',plan.id);}}>{plan.name}{plan.featured&&<Sparkle size={16}/>}</button>)}</div><div className={'plan-showcase showcase-'+p.id} key={p.id}><div className="showcase-intro"><p className="eyebrow">{p.tagline}</p><h2>{p.name}<span>{p.id==='privy'?<Diamond/>:p.id==='phoenix'?<GlobeHemisphereWest/>:<Sparkle/>}</span></h2><p>{p.description}</p><div className="showcase-price">{p.approved?money(p.pricePaise):site.settings.pricePending}</div><p className="showcase-term">{p.term} · {c.taxPending}</p>{p.id==='privy'?<a className="button primary" href={`https://wa.me/${site.settings.whatsapp}?text=${encodeURIComponent('Hi OLREADY, I would like to explore an invitation to Privy.')}`} onClick={()=>track('whatsapp_click','privy_invitation')}>{c.inviteButton}<ArrowUpRight/></a>:<Link className="button primary" href={`/checkout?plan=${p.id}`} onClick={()=>track('plan_selected',p.id)}>{c.pitchPlanCta}<ArrowRight/></Link>}<a className="text-link" href="#compare-plans">{c.pitchCompare}<ArrowRight/></a></div><div className="showcase-value"><div className="allowance"><span>{c.pitchAllowance}</span><strong>{allowance||'—'}<Sparkle weight="thin"/></strong><p>{enquiry||p.leadModel}</p></div><div className="value-facts"><div><small>{c.pitchReach}</small><strong>{p.geography}</strong></div><div><small>{c.pitchDuration}</small><strong>{p.term}</strong></div></div></div></div><div className="plan-inclusions"><h3>{c.pitchInside}</h3><ul>{p.features.map((feature,i)=><li key={i}><Check/>{feature}</li>)}</ul><details><summary>{c.pitchDetails}</summary><p>{p.leadModel}</p><p>{p.exclusions}</p><p>{p.renewal}</p></details><p className="footnote">{c.plansNote}</p></div></section>
 <section className="section pitch-belief"><div><p className="eyebrow">{c.pitchWhyEyebrow}</p><h2>{c.pitchWhyTitle}</h2><p className="pitch-intro">{c.pitchWhyBody}</p></div><div className="belief-grid">{['One','Two','Three'].map((n,i)=><article key={n}><span className="belief-number">0{i+1}</span><h3>{c['pitchWhy'+n]}</h3><p>{c['pitchWhy'+n+'Body']}</p></article>)}</div></section></div>;
}
export function HowExperience({site}:{site:Site}){
 const [step,setStep]=useState(0);const c=site.copy;const Icon=icons[step];const labels=[c.howBrief,c.howVerified,c.howDashboard,c.howConversation,c.howSupport];
 return <div className={'pitch-experience '+(!site.settings.motion?'motion-off':'')}><section className="section how-hero"><div><p className="eyebrow">{c.howEyebrow}</p><h1>{c.howTitle}</h1><p className="pitch-intro">{c.howBody}</p><div className="actions"><Link className="button primary" href="/plans">{c.howButton}<ArrowRight/></Link><a className="text-link" href={site.settings.merchantUrl} onClick={()=>track('merchant_click','how_profile')}>{c.howSecondary}<ArrowUpRight/></a></div></div><div className="how-portrait"><BrandPhoto site={site}/><div className="portrait-label"><ShieldCheck size={25}/><span>{c.howBrief}<small>{c.howStep2}</small></span></div></div></section>
 <section className="section how-walkthrough"><p className="eyebrow">{c.howWalkthrough}</p><h2>{c.howWalkthroughTitle}</h2><div className="journey-layout"><div className="journey-controls" role="group" aria-label={c.howWalkthrough}>{icons.map((_,i)=><button key={i} aria-pressed={step===i} onClick={()=>setStep(i)}><span>0{i+1}</span><strong>{c['howStep'+(i+1)]}</strong><ArrowRight size={20}/></button>)}</div><div className="journey-stage" aria-live="polite"><div className="journey-visual" key={step}><div className="journey-icon"><Icon size={62} weight="duotone"/></div><div className="mini-dashboard"><div className="mini-dashboard-bar"><span>{site.settings.brand}</span><SlidersHorizontal/></div><p>{c.howDashboard}</p><div className="mini-progress">{icons.map((Item,i)=><span className={i<=step?'done':''} key={i}><Item size={22}/></span>)}</div><strong>{labels[step]}</strong></div></div><div className="journey-description"><p className="eyebrow">{c.howStage} 0{step+1} / 05</p><h3>{c['howStep'+(step+1)]}</h3><p>{c['howBody'+(step+1)]}</p>{step<4?<button className="text-link" onClick={()=>setStep(step+1)}>{c.howNext}<ArrowRight/></button>:<Link className="text-link" href="/plans">{c.howFinish}<ArrowRight/></Link>}<small>{c.howIllustration}</small></div></div></div></section>
 <section className="section how-audience"><p className="eyebrow">{c.howAudienceEyebrow}</p><h2>{c.howAudienceTitle}</h2><div>{[1,2,3,4].map(i=><article key={i}><span>0{i}</span><h3>{c['howAudience'+i]}</h3><p>{c['howAudience'+i+'Body']}</p></article>)}</div></section><JoiningSteps site={site}/><section className="section pitch-closing"><Sparkle size={40}/><h2>{c.howClosingTitle}</h2><p>{c.howClosingBody}</p><Link href="/plans" className="button primary">{c.howButton}<ArrowRight/></Link><p className="footnote">{c.plansNote}</p></section></div>;
}
