'use client';
import {useState,useEffect,useRef} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,Check,X} from '@phosphor-icons/react';
import type {Site} from '@/lib/schema';
import {money} from '@/lib/commerce';
import {defaultPhoneCountry} from '@/lib/contact-validation';
import {PhoneFields} from './PhoneFields';
export function ProviderComparison({site}:{site:Site}){const c=site.copy;return <section className="section provider-comparison"><p className="eyebrow">{c.benefitCompareEyebrow}</p><h2>{c.benefitCompareTitle}</h2><p className="lead">{c.benefitCompareBody}</p><div className="comparison-scroll" tabIndex={0} role="region" aria-label={c.benefitCompareTitle}><table><thead><tr>{['Feature','Olready','Database','Other'].map(k=><th scope="col" key={k}>{c['benefitCompare'+k]}</th>)}</tr></thead><tbody>{[1,2,3,4,5].map(i=><tr key={i}><th scope="row">{c['benefitCompare'+i]}</th>{['Value','Database','Other'].map(k=><td key={k}>{k==='Value'&&<Check aria-hidden="true"/>}{c['benefitCompare'+i+k]}</td>)}</tr>)}</tbody></table></div><p className="footnote">{c.benefitCompareNote}</p></section>}
export function ReturnsIllustration({site}:{site:Site}){const c=site.copy;const [id,setId]=useState('pro'),[rate,setRate]=useState(5),[value,setValue]=useState(25000);const p=site.plans.find(p=>p.id===id)||site.plans[0];const allowance=Number(p.features.find(f=>/\d.*(enquir|leads)/i.test(f))?.match(/\d+/)?.[0]||0);if(!allowance||!p.approved||p.pricePaise===null)return null;const bookings=allowance*rate/100,revenue=Math.round(bookings*value*100);return <section className="section returns-illustration"><div><p className="eyebrow">{c.roiEyebrow}</p><h2>{c.roiTitle}</h2><p>{c.roiBody}</p><div className="returns-controls"><label>{c.roiPlanLabel}<select value={id} onChange={e=>setId(e.target.value)}>{site.plans.filter(p=>p.approved&&p.pricePaise!==null).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{c.roiRateLabel}<strong>{rate}%</strong><input type="range" min="5" max="10" step="1" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label>{c.roiValueLabel}<input type="number" min="0" max="10000000" step="1000" value={value} onChange={e=>setValue(Math.min(10000000,Math.max(0,Number(e.target.value))))}/></label></div></div><div className="returns-result" aria-live="polite"><span>{allowance} × {rate}% = {Number(bookings.toFixed(2))}</span><small>{c.roiBookingsLabel}</small><strong>{money(revenue)}</strong><p>{c.roiRevenueLabel}</p><dl><div><dt>{c.roiFeeLabel}</dt><dd>{money(p.pricePaise)}</dd></div><div><dt>{c.roiDifferenceLabel}</dt><dd>{money(revenue-p.pricePaise)}</dd></div></dl></div><p className="footnote">{c.roiDisclaimer}</p></section>}
export function ContactForm({site,source,defaultMessage}:{site:Site;source?:string;defaultMessage?:string}){const c=site.copy;const [error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[countryCode,setCountryCode]=useState(defaultPhoneCountry),[phoneLocal,setPhoneLocal]=useState('');const title=c.contactSuccessTitle||'Thank you — we’ve received your request';const body=c.contactSuccessBody||c.contactSuccess||'Our team will reach out shortly.';if(done)return <div className="contact-form contact-form--success" role="status"><div className="form-success"><span className="form-success-icon" aria-hidden="true"><Check size={32} weight="bold"/></span><h3>{title}</h3><p>{body}</p><div className="form-success-actions"><a className="button primary" href={`https://wa.me/${site.settings.whatsapp}`}>{c.contactSuccessWhatsapp||'Message us on WhatsApp'}<ArrowRight/></a><button type="button" className="text-button" onClick={()=>setDone(false)}>{c.contactSubmitAnother||'Send another request'}</button></div></div></div>;return <form className="contact-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=e.currentTarget;const f=new FormData(form);try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),countryCode:f.get('countryCode'),phone:f.get('phoneLocal'),email:f.get('email'),message:f.get('message'),consent:f.get('consent')==='on',source:source||window.location.pathname})});if(!res.ok)throw new Error();setDone(true);form.reset();setCountryCode(defaultPhoneCountry);setPhoneLocal('');}catch{setError(c.contactFailure);}finally{setBusy(false);}}}><label>{c.contactName}<input name="name" autoComplete="name" required maxLength={100}/></label><label>{c.contactEmail}<input name="email" type="email" autoComplete="email" maxLength={254}/></label><PhoneFields countryCode={countryCode} phoneLocal={phoneLocal} onCountryCodeChange={setCountryCode} onPhoneLocalChange={setPhoneLocal} phoneLabel={c.contactPhone}/><label>{c.contactMessage}<textarea name="message" rows={3} maxLength={1000} defaultValue={defaultMessage||''}/></label><label className="check"><input name="consent" type="checkbox" required/>{c.contactConsent}</label>{error&&<p className="form-feedback form-feedback--error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Sending…':c.contactButton}<ArrowRight/></button></form>}
export function ContactSection({site}:{site:Site}){return <section className="section contact-section" id="contact"><div><p className="eyebrow">{site.copy.contactEyebrow}</p><h2>{site.copy.contactTitle}</h2><p>{site.copy.contactBody}</p><a className="text-link" href={`https://wa.me/${site.settings.whatsapp}`}>{site.copy.whatsapp}<ArrowRight/></a>{site.settings.supportEmail&&<p><a href={`mailto:${site.settings.supportEmail}`}>{site.settings.supportEmail}</a></p>}</div><ContactForm site={site}/></section>}
export function ContactPopup({site,close}:{site:Site;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close();},[]);return <dialog ref={ref} className="contact-dialog" aria-label={site.settings.popupTitle} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close();}}><button className="icon close" onClick={close} aria-label="Close contact request"><X/></button><p className="eyebrow">{site.copy.contactEyebrow}</p><h2>{site.settings.popupTitle}</h2><p>{site.settings.popupBody}</p><ContactForm site={site}/><button className="text-button" onClick={close}>{site.copy.contactDismiss}</button></dialog>}
export function AboutPage({site}:{site:Site}){const p=site.pages.find(p=>p.slug==='/about')!;const kanika=p.sections.find(s=>s.id==='kanika');const team=p.sections.filter(s=>s.id!=='kanika');const person=(s:typeof p.sections[number],featured=false)=><article className={featured?'about-feature':'about-member'} key={s.id}><div className="team-portrait">{s.image?<Image src={s.image} alt={s.title} width={720} height={900} unoptimized/>:<span aria-label={s.title}>{s.title.split(' ').map(n=>n[0]).join('').slice(0,2)}</span>}</div><div>{s.eyebrow&&<p className="eyebrow">{s.eyebrow}</p>}<h2>{s.title}</h2>{s.designation&&<p className="team-designation">{s.designation}</p>}<p>{s.body}</p>{featured&&s.message?.trim()&&<div className="kanika-message"><h3>{site.copy.aboutMessageLabel}</h3><p>{s.message}</p></div>}{s.button&&s.href&&<Link className="text-link" href={s.href}>{s.button}<ArrowRight/></Link>}</div></article>;return <><section className="section about-people">{kanika&&person(kanika,true)}{team.length>0&&<div className="team-heading"><h2>{site.copy.aboutTeamTitle}</h2><p>{site.copy.aboutTeamBody}</p></div>}{team.map(s=>person(s))}</section><ContactSection site={site}/></>}
