export const salesCopy = {
 finderEyebrow:'A LITTLE CLARITY GOES A LONG WAY',finderTitle:'Find your next move.',finderBody:'Start with where you want to take your business. We’ll help you compare the options.',finderQuestion:'What matters most to you right now?',finderLocal:'Explore enquiries in selected states',finderNational:'Reach clients across India',finderSupport:'Explore an invitation to Privy',finderResult:'A good place to start',finderCaveat:'A starting point based on your preference. Confirm city coverage and the written plan terms with our team.',finderButton:'Explore my plan',finderHuman:'Talk it through with us',
 approachEyebrow:'YOUR TALENT. A CLEARER PATH.',approachTitle:'You bring the artistry.\nMake room for opportunity.',approachBody:'A beautiful portfolio is a beginning. What happens next is a conversation—with the right brief, in a location you serve, on terms you understand.',approachOne:'Get discovered',approachOneBody:'Build an artist profile that shows your style and the work you want to be booked for.',approachTwo:'Start a conversation',approachTwoBody:'Choose your enquiry allowance and reach. Discuss the client’s brief, timing and expectations.',approachThree:'Make it your own',approachThreeBody:'Your portfolio, availability and follow-up shape the relationship. A lead is the beginning, not a booking.',
 comparisonEyebrow:'THE DETAILS THAT MATTER',comparisonTitle:'Choose with the full picture.',comparisonBody:'Three ways to explore more opportunities. Compare the commitment, reach and support side by side.',comparisonPrice:'Plan price',comparisonTerm:'Access period',comparisonReach:'Geographical access',comparisonEnquiries:'Enquiries / leads',comparisonSupport:'Relationship manager',comparisonReversal:'Lead reversal',comparisonInvitation:'Entry',comparisonStandard:'Discuss with the team',comparisonNotListed:'Not listed in this plan',
 decisionEyebrow:'BEFORE YOU DECIDE',decisionTitle:'Good questions deserve clear answers.',decisionButton:'Explore all questions',
 closingEyebrow:'YOUR NEXT CHAPTER',closingTitle:'Let’s talk about\nyour kind of growth.',closingBody:'Tell us where you work and what you want to build. We’ll help you understand the options—without promising what a plan cannot deliver.',closingButton:'Talk to OLREADY',closingSecondary:'Compare the plans',
 planTeaserEyebrow:'ROOM FOR YOUR AMBITION',planTeaserTitle:'Your business. Your next step.',planTeaserBody:'A focused start, a wider reach, or an invitation to something more.',planTeaserButton:'See the full comparison',
 proofEmptyTitle:'Meet the people behind the results.',proofEmptyBody:'Artist stories are being prepared with their reporting periods and permissions. In the meantime, ask our team for the evidence you need to make your decision.',proofEmptyButton:'Ask about artist results',
 heroMicrocopy:'Pro, Phoenix & invite-only Privy · Explore before you choose',
};
