import type {Metadata} from 'next';import type {Site,Page} from './schema';import {featuredArtist,featuredArtists,publishedArtists} from './artist-catalog';
export const publicPaths=['/','/benefits','/top-grossing-artists','/how-it-works','/plans','/help','/about','/community','/terms','/privacy','/refunds'];
export const origin=()=>new URL(process.env.APP_URL||'http://localhost:4170').origin;
export const absolute=(path:string)=>new URL(path,origin()).href;
export const slugify=(value:string)=>value.trim().toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'').slice(0,80);
export const citySlug=(city:string)=>slugify(city);
export function artistSlug(a:Site['artists'][number]){const custom=a.slug?.trim();if(custom)return custom;return slugify(`${a.name}-${a.city}`)||a.id;}
export const artistPath=(a:Site['artists'][number])=>'/artists/'+encodeURIComponent(artistSlug(a));
export const cityPath=(city:string)=>'/makeup-artists/'+encodeURIComponent(citySlug(city));
export function resolveArtistFromPath(site:Site,path:string){if(!path.startsWith('/artists/'))return;const seg=decodeURIComponent(path.slice('/artists/'.length));return site.artists.find(a=>artistSlug(a)===seg||a.id===seg);}
export function ensureArtistSlugs(site:Site){const used=new Set<string>();for(const a of site.artists){let base=slugify(`${a.name}-${a.city}`)||a.id;let candidate=a.slug?.trim()||base;let i=2;while(used.has(candidate)&&candidate!==a.slug){candidate=`${base}-${i++}`;}a.slug=candidate;used.add(candidate);}}
export function cities(site:Site,featuredOnly=false){const pool=featuredOnly?featuredArtists(site):publishedArtists(site);return [...new Set(pool.map(a=>a.city.trim()).filter(Boolean))];}
export function directoryPage(site:Site,path:string):Page|undefined{let heading='',body='',keywords='';if(path.startsWith('/artists/')){const a=listedPeople(site).find(a=>a.url===path);if(!a)return;heading=a.name;body=a.bio||`${a.name} is a makeup artist (MUA) in ${a.city}. View their OLREADY artist profile and portfolio.`;keywords=[a.name,`makeup artist ${a.city}`,`MUA ${a.city}`,`makeupartist ${a.city}`,...(a.services||[]),a.keywords].filter(Boolean).join(', ');}else if(path.startsWith('/makeup-artists/')){const city=cities(site,true).find(c=>cityPath(c)===path);if(!city)return;heading=`Featured makeup artists in ${city}`;body=`Explore featured MUA profiles on OLREADY in ${city}. Contact OLREADY to learn more about artist results and plans.`;keywords=`makeup artist ${city}, MUA ${city}, bridal makeup ${city}`;}else return;const artistCity=path.startsWith('/artists/')?listedPeople(site).find(a=>a.url===path)?.city:'';return {slug:path,title:artistCity?`${heading} | Makeup artist in ${artistCity} | OLREADY`:`${heading} | Makeup artist | OLREADY`,description:body.slice(0,250),keywords,heading,body,eyebrow:'MEET THE ARTISTS',accent:'',primaryLabel:'Explore artists',primaryHref:'/top-grossing-artists',secondaryLabel:'Compare plans',secondaryHref:'/plans',sections:[]};}
export function artistsForPath(site:Site,path:string){const one=resolveArtistFromPath(site,path);if(one)return [one];if(path.startsWith('/makeup-artists/'))return featuredArtists(site).filter(a=>cityPath(a.city)===path);if(path==='/top-grossing-artists')return featuredArtists(site);return featuredArtists(site);}
export function metadataFor(site:Site,path:string):Metadata{const p=directoryPage(site,path)||site.pages.find(p=>p.slug===path);const selected=listedPeople(site).filter(a=>path.startsWith('/artists/')?a.url===path:path.startsWith('/makeup-artists/')?cityPath(a.city)===path&&featuredArtists(site).some(f=>f.id===a.id):path==='/top-grossing-artists'?featuredArtists(site).some(f=>f.id===a.id):false);const relevant=path==='/top-grossing-artists'||path.startsWith('/artists/')||path.startsWith('/makeup-artists/');const autoTags=relevant?selected.flatMap(a=>[...a.keywords.split(','),a.name,`MUA in ${a.city}`,`Makeup artist in ${a.city}`,`Bridal makeup artist in ${a.city}`,`Need a makeup artist in ${a.city}`,...(a.services||[]).map(service=>`${service} in ${a.city}`)]):[];const keywords=[...new Set([...(site.settings.seoKeywords||'').split(','),...(p?.keywords||'').split(','),...autoTags,...(path==='/about'?(site.pages.find(p=>p.slug==='/about')?.sections||[]).map(s=>s.title):[])].map(s=>s.trim()).filter(Boolean))];const title=p?.title||`${path.slice(1).replace(/\//g,' · ')} | OLREADY`;const description=p?.description||site.settings.footer;const image=path.startsWith('/artists/')?selected[0]?.image:site.settings.socialImage||site.settings.heroImage;const imageUrl=absolute(image||'/hero.png');const profile=path.startsWith('/artists/')&&selected[0];const openGraph={type:profile?'profile':'website',siteName:site.settings.brand,title,description,url:absolute(path),locale:'en_IN',images:[{url:imageUrl,alt:profile?selected[0]?.name||site.settings.brand:site.settings.brand}]} as Metadata['openGraph'];return {title,description,keywords,metadataBase:new URL(origin()),applicationName:site.settings.brand,category:'beauty',alternates:{canonical:absolute(path)},openGraph,twitter:{card:'summary_large_image',title,description,images:[imageUrl]},robots:path==='/checkout'?{index:false,follow:false}:{index:true,follow:true,googleBot:{index:true,follow:true,'max-image-preview':'large','max-snippet':-1}}};}
function breadcrumb(path:string,labels:[string,string][]):Record<string,unknown>|undefined{if(!labels.length)return;const last=labels[labels.length-1][1];return {'@type':'BreadcrumbList','@id':absolute(last)+'#breadcrumb',itemListElement:labels.map(([name,url],i)=>({'@type':'ListItem',position:i+1,name,item:absolute(url)}))};}
export function structuredData(site:Site,path:string){
 const organisation={'@type':'Organization','@id':absolute('/#organization'),name:site.settings.brand,url:absolute('/'),logo:absolute(site.settings.socialImage||site.settings.heroImage||'/hero.png'),description:site.settings.footer,contactPoint:{'@type':'ContactPoint',contactType:'customer support',telephone:'+'+site.settings.whatsapp,areaServed:'IN',availableLanguage:['en','hi'],description:site.settings.supportHours}};
 const graph:Record<string,unknown>[]=[organisation,{'@type':'WebSite','@id':absolute('/#website'),name:site.settings.brand,url:absolute('/'),publisher:{'@id':absolute('/#organization')},inLanguage:'en-IN'}];
 if(path==='/'){const home=site.pages.find(p=>p.slug==='/');graph.push({'@type':'WebPage','@id':absolute('/')+'#webpage',url:absolute('/'),name:home?.title||site.settings.brand,description:home?.description||site.settings.footer,isPartOf:{'@id':absolute('/#website')},about:{'@id':absolute('/#organization')},inLanguage:'en-IN'});}
 if(path==='/about')for(const s of site.pages.find(p=>p.slug==='/about')?.sections||[]){graph.push({'@type':'Person',name:s.title,...(s.designation?{jobTitle:s.designation}:{}),description:s.body,...(s.image?{image:absolute(s.image)}:{}),url:absolute('/about')});}
 const crumbs: [string,string][]=[['Home','/']];
 if(path==='/top-grossing-artists')crumbs.push(['Top Grossing Artists',path]);
 if(path.startsWith('/artists/')){crumbs.push(['Top Grossing Artists','/top-grossing-artists']);const a=listedPeople(site).find(x=>x.url===path);if(a)crumbs.push([a.name,path]);}
 if(path.startsWith('/makeup-artists/')){const city=cities(site,true).find(c=>cityPath(c)===path);if(city){crumbs.push(['Top Grossing Artists','/top-grossing-artists']);crumbs.push([`Makeup artists in ${city}`,path]);}}
 const crumb=breadcrumb(path,crumbs);if(crumb)graph.push(crumb);
 if(path==='/top-grossing-artists'||path.startsWith('/artists/')||path.startsWith('/makeup-artists/'))for(const a of listedPeople(site).filter(a=>path.startsWith('/artists/')?a.url===path:path.startsWith('/makeup-artists/')?cityPath(a.city)===path&&featuredArtists(site).some(f=>f.id===a.id):path==='/top-grossing-artists'?featuredArtists(site).some(f=>f.id===a.id):false)){graph.push({'@type':'ProfilePage','@id':absolute(a.url)+'#profile',url:absolute(a.url),name:`${a.name} | Makeup artist in ${a.city}`,description:a.bio||`${a.name}, makeup artist in ${a.city}.`,mainEntity:{'@type':'Person',name:a.name,jobTitle:'Makeup artist',description:a.bio,url:absolute(a.url),...(a.image?{image:absolute(a.image)}:{}),...(a.city?{homeLocation:{'@type':'Place',name:a.city,address:{'@type':'PostalAddress',addressLocality:a.city,addressCountry:'IN'}}}:{}),...(a.services?.length?{knowsAbout:a.services}:{}),sameAs:[a.profileUrl,a.instagram?'https://www.instagram.com/'+a.instagram.replace(/^@/,'')+'/':''].filter(Boolean)}});}
 if(path==='/plans')graph.push({'@type':'ItemList',name:'OLREADY artist plans',itemListElement:site.plans.filter(p=>p.approved).map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:absolute('/plans')+'#'+p.id}))});
 return {'@context':'https://schema.org','@graph':graph};
}
export const jsonLd=(value:unknown)=>JSON.stringify(value).replace(/</g,'\\u003c');
export function upgradeSEO(site:Site){
 site.directory??=[];ensureArtistSlugs(site);
 if(!site.pages.some(p=>p.slug==='/community'))site.pages.push({slug:'/community',title:'Our artist community | OLREADY',description:'Meet makeup artists who have been part of the OLREADY community.',eyebrow:'OUR ARTIST COMMUNITY',heading:'Meet the artists.',accent:'',body:'Explore published artist profiles, their work and the cities they serve.',primaryLabel:'Explore plans',primaryHref:'/plans',secondaryLabel:'',secondaryHref:'',sections:[]});
 if(site.copy.seoRelease!=='9'&&site.copy.seoRelease!=='10'){site.settings.supportHours='Monday to Saturday, 10:00 am–6:30 pm IST';site.settings.seoKeywords='OLREADY, makeup artists, MUA, bridal makeup artist, makeup artist plans, verified enquiries, artist profile, top grossing makeup artists India';site.settings.socialImage??='';site.copy.seoRelease='9';}
 if(site.copy.seoRelease==='10')return;
 const home=site.pages.find(p=>p.slug==='/');
 const homeDesc=home?.description||site.settings.footer;
 if(home)home.title=`${site.settings.brand} | Verified enquiries for makeup artists`;
 if(home&&!home.description?.includes('verified'))home.description=homeDesc;
 site.copy.seoRelease='10';
}
export const customerPath=(p:Site['directory'][number])=>'/community/'+encodeURIComponent(p.id);
export function listedPeople(site:Site){return site.artists.map(a=>({id:a.id,name:a.name,city:a.city,bio:a.bio||'',image:a.image,instagram:a.instagram||'',services:a.services||[],keywords:a.keywords||'',profileUrl:a.profileUrl,url:artistPath(a),featured:featuredArtist(a)}));}
export async function llmsCatalog(site:Site){const plans=site.plans.filter(p=>p.approved).map(p=>`- ${p.name}: ₹${((p.pricePaise||0)/100).toLocaleString('en-IN')} incl. GST · ${p.term}`).join('\n');const artists=publishedArtists(site).map(a=>`- ${a.name} (${a.city}): ${absolute(artistPath(a))}`).join('\n')||'- Publish artist profiles in Admin → Artists.';return [`# ${site.settings.brand} — public site map for search and assistants`,`${site.settings.tagline}`,`${site.settings.footer}`,'','## Canonical origin',absolute('/'),'','## Primary pages',...publicPaths.map(p=>`- ${absolute(p)}`),'','## Artist plans (GST-inclusive)',plans,'','## Featured makeup artists (MUA)',artists,'','## Policies',`- Terms: ${absolute('/terms')}`,`- Privacy: ${absolute('/privacy')}`,`- Refunds: ${absolute('/refunds')}`,`- Help: ${absolute('/help')}`,`- Merchant profiles: ${site.settings.merchantUrl}`,'','## Contact',`WhatsApp: +${site.settings.whatsapp}`,`Support hours: ${site.settings.supportHours}`,'','Machine-readable sitemap: '+absolute('/sitemap.xml')].join('\n');}
