import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const port=4180,base=`http://127.0.0.1:${port}`;
const fsState=await import('node:fs/promises');
const originalState=await fsState.readFile('.data/state.json','utf8');const fixture=JSON.parse(originalState);
for(const target of [fixture.draft,fixture.published]){target.directory??=[];target.directory.push({id:'qa-previous-artist',name:'QA Customer Artist',city:'QA City',bio:'Public customer profile for local testing.',profileUrl:'https://olready.in/qa',image:'/hero.png',instagram:'',services:['HD makeup'],keywords:'',approved:true,consent:true},{id:'qa-private-artist',name:'Private Test Name',city:'QA City',bio:'Not public',profileUrl:'',image:'',instagram:'',services:[],keywords:'',approved:false,consent:false});target.artists.push({id:'qa-top-artist',name:'QA Top Artist',city:'QA City',bio:'Public artist test.',profileUrl:'https://olready.in/qa-top',image:'/hero.png',instagram:'',services:['Airbrush makeup'],amountPaise:10000,definition:'Gross booking value',period:'Local test',evidence:'Local test only',consent:true,approved:true,expires:'2030-12-31T23:59:00Z',video:'',poster:'',transcript:''});}
await fsState.writeFile('.data/state.json',JSON.stringify(fixture),{mode:0o600});
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--hostname','127.0.0.1','--port',String(port)],{stdio:['ignore','pipe','pipe'],env:{...process.env,LOCAL_DEMO:'true',OPENAI_ASSISTANT_ENABLED:'false'}});
let logs='';for(const stream of [server.stdout,server.stderr])stream.on('data',b=>{logs+=b.toString();});
try{
 let ready=false;for(let i=0;i<50;i++){try{const r=await fetch(base);if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,200));}if(!ready)console.error(logs);assert.ok(ready,'Local server did not become ready');
 const expected={'/':'More client conversations.','/benefits':'More than visibility.','/plans':'A clear plan.','/how-it-works':'From a client','/top-grossing-artists':'Top Grossing Artists','/checkout':'Total including GST','/help':'Good questions.','/about':'Kanika Khanna','/community':'Meet the artists.','/artists/qa-top-artist':'QA Top Artist','/community/qa-previous-artist':'QA Customer Artist','/makeup-artists/qa-city':'Makeup artists in QA City'};
 for(const [path,phrase] of Object.entries(expected)){const r=await fetch(base+path);assert.equal(r.status,200,path);const html=await r.text();assert.ok(html.includes(phrase),path+' missing current content');assert.ok(!html.includes('Tax treatment to be confirmed'),path+' has stale tax wording');if(path==='/'){assert.ok(html.includes('src="/hero.png"'),'hero is not a direct bundled image');const style=html.match(/href="([^"]+\.css[^\"]*)"/);assert.ok(style,'missing stylesheet');const css=await fetch(base+style[1].replaceAll('&amp;','&'));assert.equal(css.status,200);assert.match(await css.text(),/sales-hero/);}}
 const benefits=(await (await fetch(base+'/benefits')).text()).replace(/<script[\s\S]*?<\/script>/g,'');assert.ok(benefits.includes('Database providers'));assert.ok(benefits.includes('Only active leads'));assert.ok(!benefits.includes('Minimum client budget'));assert.ok(benefits.includes('>RM<'));
 const plans=await (await fetch(base+'/plans')).text();assert.ok(plans.includes('All lead budgets accessible'));assert.ok(plans.includes('₹75,000'));assert.ok(plans.includes('₹56,001'));
 const headers={Origin:base,'Content-Type':'application/json'};const payload={name:'QA contact verification',phone:'9999999999',message:'Automated local test',source:'/help',consent:true};
 const denied=await fetch(base+'/api/contact',{method:'POST',headers,body:JSON.stringify({...payload,consent:false})});assert.equal(denied.status,400);
 const cross=await fetch(base+'/api/contact',{method:'POST',headers:{...headers,Origin:'https://untrusted.example'},body:JSON.stringify(payload)});assert.equal(cross.status,400);
 const created=await fetch(base+'/api/contact',{method:'POST',headers,body:JSON.stringify(payload)});assert.equal(created.status,200);
 const admin=await (await fetch(base+'/api/admin')).json();const contact=admin.contacts.find(c=>c.name===payload.name);assert.ok(contact);assert.equal(contact.status,'new');
 const changed=await fetch(base+'/api/contact/status',{method:'POST',headers,body:JSON.stringify({id:contact.id,status:'contacted'})});assert.equal(changed.status,200);const updated=await (await fetch(base+'/api/admin')).json();assert.equal(updated.contacts.find(c=>c.id===contact.id).status,'contacted');
 const fs=await import('node:fs/promises');const state=JSON.parse(await fs.readFile('.data/state.json','utf8'));state.contacts=state.contacts.filter(c=>c.id!==contact.id);await fs.writeFile('.data/state.json',JSON.stringify(state,null,2),{mode:0o600});
 const metaHTML=await (await fetch(base+'/community/qa-previous-artist',{headers:{'User-Agent':'facebookexternalhit/1.1'}})).text();const head=metaHTML.split('</head>')[0];assert.ok(head.includes('og:title'));assert.ok(head.includes('og:image'));assert.ok(head.includes('rel="canonical"'));assert.ok(head.includes('HD makeup in QA City'));assert.ok(metaHTML.includes('application/ld+json'));assert.ok(metaHTML.includes('6:30 pm IST'));
 const sitemap=await (await fetch(base+'/sitemap.xml')).text();assert.ok(sitemap.includes('/artists/qa-top-artist'));assert.ok(sitemap.includes('/community/qa-previous-artist'));assert.ok(sitemap.includes('/makeup-artists/qa-city'));assert.ok(!sitemap.includes('qa-private-artist'));assert.ok(!sitemap.includes('/checkout'));assert.equal((await fetch(base+'/community/qa-private-artist')).status,404);const robots=await (await fetch(base+'/robots.txt')).text();assert.ok(robots.includes('Allow: /'));assert.ok(robots.includes('sitemap.xml'));const config=await (await fetch(base+'/api/assistant/knowledge')).json();assert.equal(config.enabled,false);assert.ok(!('apiKey' in config));const bad=await fetch(base+'/api/assistant/knowledge',{method:'POST',headers:{Origin:'https://invalid.example','Content-Type':'application/json'},body:JSON.stringify({action:'setup'})});assert.equal(bad.status,400);
 const image=await fetch(base+'/hero.png');assert.equal(image.status,200);assert.ok(Number(image.headers.get('content-length'))>100000);assert.match(image.headers.get('content-type'),/image/);
 const signing=await fetch(base+'/api/media/sign',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({type:'image/png',size:200})});assert.equal(signing.status,200);assert.equal((await signing.json()).mode,'local');
 const mediaBytes=await (await import('node:fs/promises')).readFile('public/hero.png');const uploadBody=new FormData();uploadBody.append('file',new Blob([mediaBytes],{type:'image/png'}),'qa-portrait.png');const upload=await fetch(base+'/api/media',{method:'POST',headers:{Origin:base},body:uploadBody});assert.equal(upload.status,200);const media=await upload.json();assert.match(media.url,/^\/uploads\/[a-f0-9-]+\.png$/);try{const delivered=await fetch(base+media.url);assert.equal(delivered.status,200);assert.equal((await delivered.arrayBuffer()).byteLength,mediaBytes.length);}finally{await (await import('node:fs/promises')).unlink('public'+media.url);}
 const api=await fetch(base+'/api/assistant',{method:'POST',headers:{Origin:base,'Content-Type':'application/json'},body:JSON.stringify({message:'Does Pro include GST?'})});assert.equal(api.status,200);assert.match((await api.json()).answer,/include 18% GST/);
 console.log('PASS: marketing, individual artist, customer and city pages; Meta crawler head tags, JSON-LD, sitemap, private draft exclusion, AI configuration/invalid origin; comparison, RM label, removed budget filter, returns illustration, contact validation/admin status flow; current sales content, direct bundled image and stylesheet served; no stale tax wording; GST guide endpoint and local media signing/upload/read-back verified.');
}finally{server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));await fsState.writeFile('.data/state.json',originalState,{mode:0o600});}
